name: Build and push container images

on:
  workflow_dispatch:
  pull_request:
    types:
      # - auto_merge_enabled
      - labeled
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - main

env:
  IMAGE_TAGS: |
    type=schedule
    type=semver,pattern={{version}}
    type=semver,pattern={{major}}.{{minor}}
    type=semver,pattern={{major}}
    type=ref,event=branch
    type=ref,event=pr
    type=sha
    type=raw,value=latest,enable={{is_default_branch}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            okdas/pocket-v1
            ghcr.io/okdas/pocket-v1
          tags: ${{ env.IMAGE_TAGS }}
      - name: Login to  DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          # context: build/
          file: build/Dockerfile.prod
